#!/bin/bash

if test $SSH_AUTH_SOCK; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/sockets/$(hostname -s)
fi

if read proto cookie && [ -n "$DISPLAY" ]; then
        if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
                # X11UseLocalhost=yes
                echo add unix:`echo $DISPLAY |
                    cut -c11-` $proto $cookie
        else
                # X11UseLocalhost=no
                echo add $DISPLAY $proto $cookie
        fi | xauth -q -
fi
